### ISSUE TITLE
Seekbar Component should be accessible for new modules

### ISSUE THREAD

**Issue by stoicbuddha** [matvp91/indigo-player#33] opened 2019-05-13 16:33 UTC
I am currently trying to create a module for displaying BIF files, which work approximately the same way the `thumbnails.vtt` file works in the docs. Unfortunately, I don't seem to have a decent way of accessing the same components you used for creating the Thumbnail module. 

What I would like to see is a way to bring this into new modules so I can figure out hover position and draw elements near it.

**Comment by matvp91** [comment] 2019-05-14 08:37
The UI extension is built in a way that it can get data from other modules, but not the other way around. Modules cannot change how or what the UI extension displays (as this is solely the UI's responsibility).

Easiest would be to extend the thumbnails extension itself (https://github.com/matvp91/indigo-player/blob/master/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts) and keep the `getThumbnail(seconds)` method in sync. Aslong as it returns a `IThumbnail` compatible object, the UI will respect this and show the proper thumbnail.

**Comment by stoicbuddha** [comment] 2019-05-14 16:44
I'm not entirely clear on how to do that. I'm new to Typescript (normally work in vanilla JS) so maybe I'm missing something. I'm importing it, like so:

`import { ThumbnailsExtension } from 'indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension';`

And extending it, like so:

`export class BifExtension extends ThumbnailsExtension`

And immediately get a bunch of console errors from webpack:

```
ERROR in ./node_modules/indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts
Module not found: Error: Can't resolve '@src/Module' in '/private/var/www/player-pocs/indigo-full/modules/bif/node_modules/indigo-player/src/extensions/ThumbnailsExtension'
 @ ./node_modules/indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts 49:0-37 103:2-8
 @ ./src/BifExtension.ts
 @ ./src/BifExtensionLoader.ts
 @ ./src/index.ts

ERROR in [at-loader] ./node_modules/indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts:1:24 
    TS2307: Cannot find module '@src/Module'.

ERROR in [at-loader] ./node_modules/indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts:2:59 
    TS2307: Cannot find module '@src/types'.

ERROR in [at-loader] ./node_modules/indigo-player/src/extensions/ThumbnailsExtension/ThumbnailsExtension.ts:18:23 
    TS2339: Property 'instance' does not exist on type 'ThumbnailsExtension'.

ERROR in [at-loader] ./src/index.ts:4:17 
    TS2345: Argument of type '{ type: ModuleLoaderTypes; create: (instance: any) => BifExtension; isSupported: ({ config }: { config: any; }) => boolean; }' is not assignable to parameter of type 'IModuleLoader<IModule>'.
  Types of property 'create' are incompatible.
    Type '(instance: any) => BifExtension' is not assignable to type '(instance: IInstance) => IModule | Promise<IModule>'.
      Type 'BifExtension' is not assignable to type 'IModule | Promise<IModule>'.
        Type 'BifExtension' is missing the following properties from type 'IModule': instance, on, once, emit
```

**Comment by matvp91** [comment] 2019-05-14 18:32
That's not exactly how it works. indigo-player has a bunch of default extensions to add additional logic to the player. One of the extensions is the ThumbnailsExtension (responsible for fetching the thumbnails and providing an API for other extensions to get the correct thumbnail at a specific point in time).

Extensions should be isolated and do not contain any hard references to other extensions by design.

I suggest you fork the project (& run it with `yarn && yarn run dev`), and add support for BIF right in the `ThumbnailsExtension`.

If you'd rather write your own custom extension, I'll have to add a config variable that will exclude the default `ThumbnailsExtension` from loading, which would allow you to inject your own with the `IndigoPlayer.addModuleLoader` API.

Let me know if you'd rather write your own custom extension to handle thumbnails (https://matvp91.github.io/indigo-player/#/CreateAModule) or if you'd like to extend the base thumbnails functionality with support for BIF.

**Comment by stoicbuddha** [comment] 2019-05-14 18:36
I think it would make more sense to just extend the current plugin. I'll get started on a PR (I already forked the project).

**Comment by matvp91** [comment] 2019-05-14 18:44
I've pushed a restriction on the ThumbnailsExtension so that it only loads when the thumbnails source ends with `.vtt`, implementation is here: https://github.com/matvp91/indigo-player/blob/master/src/extensions/ThumbnailsExtension/ThumbnailsExtensionLoader.ts#L20

You'd basically have to add your extension (.bif?) and decide how you'll handle both cases in the `ThumbnailsExtension`. Aslong as the `getThumbnail` API provides a valid `IThumbnail`, you're good to go. :)

**Comment by stoicbuddha** [comment] 2019-05-14 21:23
PR Submitted: https://github.com/matvp91/indigo-player/pull/36

**Comment by matvp91** [comment] 2019-05-15 19:23
@stoicbuddha v1.4.0 is released with BIF support (your PR) included.

**Closed** 2019-05-15 19:23 UTC
